In [1]:
import tensorflow as tf

# 4.1数据类型

### 4.1.1 数值类型

###### 创建标量

In [4]:
a=1.2
aa=tf.constant(1.2)

In [5]:
type(a),type(aa),tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

###### 打印信息

In [6]:
x=tf.constant([1.2,3.3])

In [7]:
x

<tf.Tensor: id=2, shape=(2,), dtype=float32, numpy=array([1.2, 3.3], dtype=float32)>

In [8]:
x.numpy()

array([1.2, 3.3], dtype=float32)

###### 创建向量

In [9]:
a=tf.constant([1.2])

In [10]:
a,a.shape

(<tf.Tensor: id=3, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

###### 创建两个元素的向量

In [12]:
a=tf.constant([1.2,3.])

In [13]:
a,a.shape

(<tf.Tensor: id=5, shape=(2,), dtype=float32, numpy=array([1.2, 3. ], dtype=float32)>,
 TensorShape([2]))

###### 创建矩阵

In [14]:
a=tf.constant([[1,2],[3,4],[5,6],[7,8]])

In [15]:
a,a.shape

(<tf.Tensor: id=6, shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])>, TensorShape([4, 2]))

### 4.1.2 字符串类型

In [19]:
a=tf.constant('Hello, Deep Learning.')

In [20]:
a

<tf.Tensor: id=9, shape=(), dtype=string, numpy=b'Hello, Deep Learning.'>

In [21]:
tf.strings.lower(a)

<tf.Tensor: id=10, shape=(), dtype=string, numpy=b'hello, deep learning.'>

### 4.1.3 布尔类型

In [3]:
a=tf.constant(True)

In [4]:
a

<tf.Tensor: id=0, shape=(), dtype=bool, numpy=True>

In [5]:
a=tf.constant([True,True])

In [6]:
a

<tf.Tensor: id=1, shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [19]:
a = tf.constant(True)

In [28]:
## 奇怪
a==True

<tf.Tensor: id=26, shape=(), dtype=bool, numpy=True>

# 4.2 数值精度

###### 指定保存精度

In [30]:
tf.constant(123456789,dtype=tf.int16)

<tf.Tensor: id=27, shape=(), dtype=int16, numpy=-13035>

In [31]:
tf.constant(123456789,dtype=tf.int32)

<tf.Tensor: id=28, shape=(), dtype=int32, numpy=123456789>

In [33]:
import numpy as np

In [34]:
np.pi

3.141592653589793

In [35]:
tf.constant(np.pi,dtype=tf.float32)

<tf.Tensor: id=29, shape=(), dtype=float32, numpy=3.1415927>

In [36]:
tf.constant(np.pi,dtype=tf.float64)

<tf.Tensor: id=30, shape=(), dtype=float64, numpy=3.141592653589793>

### 4.2.1 读取精度

In [37]:
print('before:',a.dtype)

before: <dtype: 'bool'>


In [38]:
if a.dtype!=tf.float32:
    a=tf.cast(a,tf.float32)

In [39]:
print('after:',a.dtype)

after: <dtype: 'float32'>


### 4.2.2 类型转换

In [41]:
a=tf.constant(np.pi,dtype=tf.float32)

In [42]:
tf.cast(a,tf.double)

<tf.Tensor: id=33, shape=(), dtype=float64, numpy=3.1415927410125732>

In [43]:
a=tf.constant(123456789,dtype=tf.int16)

In [44]:
tf.cast(a,tf.int16)

<tf.Tensor: id=34, shape=(), dtype=int16, numpy=-13035>

In [45]:
a=tf.constant([True,False])

In [46]:
tf.cast(a,tf.int32)

<tf.Tensor: id=36, shape=(2,), dtype=int32, numpy=array([1, 0])>

In [47]:
a=tf.constant([-1,0,1,2])
tf.cast(a,tf.bool)

<tf.Tensor: id=38, shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

# 4.3 待优化的张量

###### 转化张量

In [48]:
a=tf.constant([-1,0,1,2])

In [49]:
aa=tf.Variable(a)

In [50]:
aa.name,aa.trainable

('Variable:0', True)

###### 直接创建

In [53]:
a=tf.Variable([[1,2],[3,4]])

In [54]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

# 4.4 创建张量

### 4.4.1 从Numpy,List对象创建

In [55]:
tf.convert_to_tensor([1,2.])

<tf.Tensor: id=63, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [56]:
tf.convert_to_tensor(np.array([[1,2.],[3,4]]))

<tf.Tensor: id=64, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

### 4.4.2 创建全0，全1张量

###### 创建为0和为1的标量张量

In [57]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: id=65, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=66, shape=(), dtype=float32, numpy=1.0>)

###### 创建为0和为1的向量

In [58]:
tf.zeros([1]),tf.ones([1])

(<tf.Tensor: id=69, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=72, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

###### 创建为0和为1的矩阵

In [59]:
tf.zeros([2,2]),tf.ones([2,2])

(<tf.Tensor: id=75, shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>,
 <tf.Tensor: id=78, shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

###### `tf.zeros_like`,`tf.ones_like`

In [60]:
a=tf.ones([2,3])

In [61]:
a

<tf.Tensor: id=81, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [62]:
tf.zeros_like(a)

<tf.Tensor: id=82, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [63]:
a=tf.zeros([3,2])

In [64]:
tf.ones_like(a)

<tf.Tensor: id=88, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [65]:
tf.ones(a.shape)

<tf.Tensor: id=91, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

### 4.4.3 创建自定义数值张量

In [66]:
tf.fill([],-1)

<tf.Tensor: id=94, shape=(), dtype=int32, numpy=-1>

In [67]:
tf.fill([1],-1)

<tf.Tensor: id=97, shape=(1,), dtype=int32, numpy=array([-1])>

In [68]:
tf.fill([2,2],99)

<tf.Tensor: id=100, shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]])>

### 4.4.4 创建已知分布的张量

In [69]:
tf.random.normal([2,2])

<tf.Tensor: id=106, shape=(2, 2), dtype=float32, numpy=
array([[-0.1744725, -0.5385291],
       [-1.1669066, -0.614885 ]], dtype=float32)>

In [70]:
tf.random.normal([2,2],mean=1,stddev=2)

<tf.Tensor: id=112, shape=(2, 2), dtype=float32, numpy=
array([[ 1.4998832 , -2.1224077 ],
       [-0.48446262,  1.5623707 ]], dtype=float32)>

In [71]:
tf.random.uniform([2,2])

<tf.Tensor: id=119, shape=(2, 2), dtype=float32, numpy=
array([[0.91567063, 0.5413915 ],
       [0.12689126, 0.36527383]], dtype=float32)>

In [72]:
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: id=126, shape=(2, 2), dtype=float32, numpy=
array([[3.0709064, 5.937681 ],
       [4.682399 , 4.3753552]], dtype=float32)>

In [73]:
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: id=130, shape=(2, 2), dtype=int32, numpy=
array([[92, 97],
       [91, 83]])>

### 4.4.5 创建序列

In [74]:
tf.range(10)

<tf.Tensor: id=134, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [75]:
tf.range(10,delta=2)

<tf.Tensor: id=138, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [76]:
tf.range(1,10,delta=2)

<tf.Tensor: id=142, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

# 4.5 张量的典型应用

### 4.5.1 标量

In [79]:
out=tf.random.uniform([4,10])
y=tf.constant([2,3,2,0])
y=tf.one_hot(y,depth=10)
loss=tf.keras.losses.mse(y,out)
loss=tf.reduce_mean(loss)
print(loss)

tf.Tensor(0.3303818, shape=(), dtype=float32)


### 4.5.2 向量

In [80]:
z=tf.random.normal([4,2])
b=tf.zeros([2])
z=z+b

In [81]:
z

<tf.Tensor: id=198, shape=(4, 2), dtype=float32, numpy=
array([[ 0.5164533 ,  0.99801165],
       [-1.518929  , -0.40234238],
       [ 0.0483851 , -0.2556248 ],
       [-1.3166676 ,  0.35266334]], dtype=float32)>

In [82]:
fc=tf.keras.layers.Dense(3)

In [83]:
fc.build(input_shape=(2,4))

In [84]:
fc.bias

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [85]:
fc.weights

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.38671887,  0.7745857 ,  0.7415507 ],
        [ 0.3422209 , -0.37515002,  0.40419245],
        [-0.9185516 ,  0.8985206 ,  0.50827396],
        [ 0.8307657 ,  0.882306  ,  0.02594292]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [86]:
fc.variables

[<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.38671887,  0.7745857 ,  0.7415507 ],
        [ 0.3422209 , -0.37515002,  0.40419245],
        [-0.9185516 ,  0.8985206 ,  0.50827396],
        [ 0.8307657 ,  0.882306  ,  0.02594292]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

### 4.5.3 矩阵

In [87]:
x=tf.random.normal([2,4])

In [88]:
w=tf.ones([4,3])
b=tf.zeros([3])

In [89]:
o=x@w+b

In [90]:
o

<tf.Tensor: id=313, shape=(2, 3), dtype=float32, numpy=
array([[-1.0144649, -1.0144649, -1.0144649],
       [-3.338842 , -3.338842 , -3.338842 ]], dtype=float32)>

In [91]:
o=tf.matmul(x,w)+b

In [92]:
o

<tf.Tensor: id=315, shape=(2, 3), dtype=float32, numpy=
array([[-1.0144649, -1.0144649, -1.0144649],
       [-3.338842 , -3.338842 , -3.338842 ]], dtype=float32)>

In [93]:
fc=tf.keras.layers.Dense(3)
fc.build(input_shape=(2,4))
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.5843638 ,  0.3989483 , -0.40629452],
       [ 0.70317054, -0.8604932 , -0.5025356 ],
       [ 0.37166977, -0.00205284, -0.6489451 ],
       [ 0.6389364 , -0.65765727,  0.41210997]], dtype=float32)>

### 4.5.4 3维张量

In [94]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.imdb.load_data(num_words=10000)

In [98]:
len(x_train[0]),len(x_train[1])

(218, 189)

In [99]:
x_train=tf.keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)

In [100]:
x_train.shape

(25000, 80)

In [101]:
embedding=tf.keras.layers.Embedding(10000,100)

In [102]:
out=embedding(x_train)

In [103]:
out.shape

TensorShape([25000, 80, 100])

### 4.5.5 4维张量

In [105]:
x=tf.random.normal([4,32,32,3])

In [106]:
layer=tf.keras.layers.Conv2D(16,kernel_size=3)
out=layer(x)
out.shape

TensorShape([4, 30, 30, 16])

In [107]:
layer.kernel.shape

TensorShape([3, 3, 3, 16])

# 4.6 索引与切片

### 4.6.1 索引

In [108]:
x=tf.random.normal([4,32,32,3])

In [111]:
x[0];

In [113]:
x[0][1];

In [115]:
x[0][1][2];

In [117]:
x[2][1][0][1];

In [119]:
x[1,9,2];

### 4.6.1 切片

In [121]:
x[1:3].shape

TensorShape([2, 32, 32, 3])

In [122]:
x[0,::].shape

TensorShape([32, 32, 3])

In [123]:
x[:,0:28:2,0:28:2,:].shape

TensorShape([4, 14, 14, 3])

In [124]:
x=tf.range(9)

In [125]:
x[8:0:-1]

<tf.Tensor: id=509, shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1])>

In [126]:
x[::-1]

<tf.Tensor: id=513, shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0])>

In [127]:
x[::-2]

<tf.Tensor: id=517, shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0])>

In [128]:
x=tf.random.normal([4,32,32,3])

In [130]:
x[0,::-2,::-2].shape

TensorShape([16, 16, 3])

In [131]:
x[:,:,:,1].shape

TensorShape([4, 32, 32])

In [133]:
x[0:2,...,1:].shape

TensorShape([2, 32, 32, 2])

In [134]:
x[2:,...].shape

TensorShape([2, 32, 32, 3])

In [135]:
x[...,:2].shape

TensorShape([4, 32, 32, 2])

# 4.7 维度变换

### 4.7.1 Reshape

In [146]:
x=tf.range(96)

In [147]:
x.shape

TensorShape([96])

In [148]:
x

<tf.Tensor: id=566, shape=(96,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])>

In [149]:
x=tf.reshape(x,[2,4,4,3])

In [150]:
x.shape

TensorShape([2, 4, 4, 3])

In [151]:
x

<tf.Tensor: id=568, shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

In [152]:
x.ndim,x.shape

(4, TensorShape([2, 4, 4, 3]))

In [153]:
tf.reshape(x,[2,-1])

<tf.Tensor: id=570, shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])>

In [154]:
tf.reshape(x,[2,4,12])

<tf.Tensor: id=572, shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]])>

In [155]:
tf.reshape(x,[2,-1,3])

<tf.Tensor: id=574, shape=(2, 16, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95]]])>

### 4.7.2 增删维度

In [156]:
x=tf.random.uniform([28,28],maxval=10,dtype=tf.int32)

In [158]:
x.shape

TensorShape([28, 28])

In [159]:
x=tf.expand_dims(x,axis=2)

In [160]:
x.shape

TensorShape([28, 28, 1])

In [162]:
x=tf.expand_dims(x,axis=0)

In [163]:
x.shape

TensorShape([1, 28, 28, 1])

In [164]:
x=tf.squeeze(x,axis=0)

In [165]:
x.shape

TensorShape([28, 28, 1])

In [166]:
x=tf.squeeze(x,axis=2)

In [167]:
x.shape

TensorShape([28, 28])

In [168]:
x=tf.random.uniform([1,28,28,1],maxval=10,dtype=tf.int32)

In [170]:
x.shape

TensorShape([1, 28, 28, 1])

In [171]:
tf.squeeze(x).shape

TensorShape([28, 28])

### 4.7.3 交换维度

In [176]:
x=tf.random.normal([2,32,32,3])

In [177]:
x.shape

TensorShape([2, 32, 32, 3])

In [178]:
tf.transpose(x,perm=[0,3,1,2]).shape

TensorShape([2, 3, 32, 32])

In [179]:
tf.transpose(x,perm=[0,2,1,3]).shape

TensorShape([2, 32, 32, 3])

### 4.7.4 数据复制

In [186]:
b=tf.constant([1,2])
b=tf.expand_dims(b,axis=0)
b

<tf.Tensor: id=627, shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [187]:
b=tf.tile(b,multiples=[2,1])
b

<tf.Tensor: id=629, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]])>

In [188]:
x=tf.range(4)

In [189]:
x=tf.reshape(x,[2,2])

In [190]:
x

<tf.Tensor: id=635, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [191]:
x=tf.tile(x,multiples=[1,2])
x

<tf.Tensor: id=637, shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [192]:
x=tf.tile(x,multiples=[2,1])
x

<tf.Tensor: id=639, shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])>

# 4.8 Broadcasting

In [195]:
x=tf.random.normal([2,4])
w=tf.random.normal([4,3])
b=tf.random.normal([3])
y=x@w+b
y

<tf.Tensor: id=837, shape=(2, 3), dtype=float32, numpy=
array([[ 0.17257673,  1.5890493 , -0.6791984 ],
       [ 3.4014895 ,  1.2983836 ,  0.4201851 ]], dtype=float32)>

In [197]:
y=x@w+tf.broadcast_to(b,[2,3])
y

<tf.Tensor: id=845, shape=(2, 3), dtype=float32, numpy=
array([[ 0.17257673,  1.5890493 , -0.6791984 ],
       [ 3.4014895 ,  1.2983836 ,  0.4201851 ]], dtype=float32)>

In [199]:
A=tf.random.normal([32,1])
tf.broadcast_to(A,[2,32,32,3]).shape

TensorShape([2, 32, 32, 3])

In [200]:
A=tf.random.normal([32,2])
tf.broadcast_to(A,[2,32,32,3]).shape

InvalidArgumentError: Incompatible shapes: [32,2] vs. [2,32,32,3] [Op:BroadcastTo]

In [202]:
a=tf.random.normal([2,32,32,1])
b=tf.random.normal([32,32])


In [203]:
(a+b).shape,(a-b).shape,(a*b).shape,(a/b).shape

(TensorShape([2, 32, 32, 32]),
 TensorShape([2, 32, 32, 32]),
 TensorShape([2, 32, 32, 32]),
 TensorShape([2, 32, 32, 32]))

# 4.9 数学运算

### 4.9.1 加减乘除

In [204]:
a=tf.range(5)
b=tf.constant(2)

In [205]:
a//b

<tf.Tensor: id=906, shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2])>

In [206]:
a%b

<tf.Tensor: id=907, shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0])>

### 4.9.2 乘方

In [207]:
x=tf.range(4)
tf.pow(x,3)

<tf.Tensor: id=913, shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27])>

In [208]:
x**2

<tf.Tensor: id=915, shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9])>

In [210]:
x=tf.constant([1.,4.,9.,])
x**(0.5)

<tf.Tensor: id=919, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [212]:
x=tf.range(5)
x=tf.cast(x,dtype=tf.float32)
x=tf.square(x)
x

<tf.Tensor: id=931, shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

In [213]:
tf.sqrt(x)

<tf.Tensor: id=932, shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

### 4.9.3 指数、对数

In [214]:
x=tf.constant([1.,2.,3.])
2**x

<tf.Tensor: id=935, shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

In [215]:
tf.exp(1.)

<tf.Tensor: id=937, shape=(), dtype=float32, numpy=2.7182817>

In [216]:
x=tf.exp(1.)
tf.math.log(x)

<tf.Tensor: id=940, shape=(), dtype=float32, numpy=1.0>

In [217]:
x=tf.constant([1.,2.])
x=10**x
tf.math.log(x)/tf.math.log(10.)

<tf.Tensor: id=947, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### 4.9.4 矩阵相乘

In [218]:
a=tf.random.normal([4,3,23,32])
b=tf.random.normal([4,3,32,2])

In [220]:
(a@b).shape

TensorShape([4, 3, 23, 2])

In [225]:
a=tf.random.normal([4,28,32])
b=tf.random.normal([32,16])

In [226]:
(a@b).shape

TensorShape([4, 28, 16])