# 01TensorFlow常量变量
1. 类比 语法 api 原理
1. 基础数据类型 运算符 流程 字典 数组

In [4]:
import tensorflow as tf
data1=tf.constant(2.5)
data2=tf.Variable(10,name='var')
print(data1)
print(data2)
sess=tf.Session()
print(sess.run(data1))

Tensor("Const_2:0", shape=(), dtype=float32)
<tf.Variable 'var_2:0' shape=() dtype=int32_ref>
2.5


In [6]:
data1=tf.constant(2,dtype=tf.int32)
data2=tf.Variable(10,name='var')
print(data1)
print(data2)
sess=tf.Session()
print(sess.run(data1))  

Tensor("Const_3:0", shape=(), dtype=int32)
2


In [7]:
data1=tf.constant(2,dtype=tf.int32)
data2=tf.Variable(10,name='var')
# print(data1)
print(data2)
sess=tf.Session() 
print(sess.run(data2))# error Attempting to use uninitialized value var_3 变量要初始化

<tf.Variable 'var_3:0' shape=() dtype=int32_ref>


FailedPreconditionError: Attempting to use uninitialized value var_3
	 [[{{node _retval_var_3_0_0}} = _Retval[T=DT_INT32, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](var_3)]]

In [8]:
import tensorflow as tf
data1=tf.constant(2,dtype=tf.int32)
data2=tf.Variable(10,name='var')
print(data1)
print(data2)
sess=tf.Session()
print(sess.run(data1))
# 对变量进行初始化
init=tf.global_variables_initializer()
sess.run(init)
print(sess.run(data2))

Tensor("Const_5:0", shape=(), dtype=int32)
<tf.Variable 'var_4:0' shape=() dtype=int32_ref>
2
10


# 02Tensorflow 工作原理
1. 实质 张量tensor+计算图graphs
1. tensor 数据
1. op
1. graphs 数据操作
1. session 运算的交互环境
1. 所有变量必须初始化才能使用
1. session 需要close  或者 with

In [9]:
import tensorflow as tf
data1=tf.constant(2,dtype=tf.int32)
data2=tf.Variable(10,name='var')
print(data1)
print(data2)
'''
sess=tf.Session()
print(sess.run(data1))
# 对变量进行初始化
init=tf.global_variables_initializer()
sess.run(init)
print(sess.run(data2))
'''
init=tf.global_variables_initializer()
sess=tf.Session()
with sess:
    sess.run(init)
    print(sess.run(data2))

Tensor("Const_6:0", shape=(), dtype=int32)
<tf.Variable 'var_5:0' shape=() dtype=int32_ref>
10


# 03Tensorflow 四则运算

# 常量四则运算

In [10]:
import tensorflow as tf
data1=tf.constant(6)
data2=tf.constant(12)
dataAdd=tf.add(data1,data2)
dataMul=tf.multiply(data1,data2)
dataSub=tf.subtract(data1,data2)
dataDiv=tf.divide(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
print("end!")

18
72
-6
0.5
end!


# 变量四则运算

In [11]:
import tensorflow as tf
data1=tf.constant(6)
data2=tf.Variable(2)
dataAdd=tf.add(data1,data2)
dataMul=tf.multiply(data1,data2)
dataSub=tf.subtract(data1,data2)
dataDiv=tf.divide(data1,data2)
init=tf.global_variables_initializer()
with tf.Session() as sess:
    print(sess.run(init))
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
print("end!")

None
8
12
4
3.0
end!


# 数据更新

In [13]:
import tensorflow as tf
data1=tf.constant(6)
data2=tf.Variable(2)
dataAdd=tf.add(data1,data2)
dataCopy=tf.assign(data2,dataAdd) # dataAdd->data2
dataMul=tf.multiply(data1,data2)
dataSub=tf.subtract(data1,data2)
dataDiv=tf.divide(data1,data2)
init=tf.global_variables_initializer()
with tf.Session() as sess:
    print(sess.run(init))
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
    print('sess.run(dataCopy)',sess.run(dataCopy)) #8->data2
    print('dataCopy.eval()',dataCopy.eval()) #8+6=>14 -> data2=14
    print('tf.get_default_session.run(dataCopy)',tf.get_default_session().run(dataCopy))
    
print("end!")

None
8
12
4
3.0
sess.run(dataCopy) 8
dataCopy.eval() 14
tf.get_default_session.run(dataCopy) 20
end!


# 04Tensorflow 矩阵定义与读取
1. placehold

In [14]:
import tensorflow as tf
data1=tf.placeholder(tf.float32)
data2=tf.placeholder(tf.float32)
dataAdd=tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd,feed_dict={data1:6,data2:2}))
    # 1.dataAdd 2. data (feed_dict={1:6，2:2})
print('end!')

8.0
end!


In [20]:
# 类比 矩阵就是数组 M行N列 []  内部[] [里面 列数据]
#[[6,6]] 1行两列的矩阵
import tensorflow as tf
data1 = tf.constant([[6,6]] )
data2 = tf.constant([[2],
                      [2]] )
data3 = tf.constant([[3,3]] )
data4 = tf.constant([[1,2],
                     [3,4],
                     [5,6]] )

print(data4.shape) # 打印维度
with tf.Session() as sess:
    print(sess.run(data4))
    print(sess.run(data4[0])) #打印某一行
    print(sess.run(data4[:,0])) #打印某一列
    print(sess.run(data4[0,0])) #打印某一个 MN = 0
    
print('end!')  

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1
end!


# 05Tensorflow 矩阵运算
1. 必须行列相等
 

In [25]:
# 类比 矩阵就是数组 M行N列 []  内部[] [里面 列数据]
#[[6,6]] 1行两列的矩阵
import tensorflow as tf
data1 = tf.constant([[6,6]] )
data2 = tf.constant([[2],
                      [2]] )
data3 = tf.constant([[3,3]] )
data4 = tf.constant([[1,2],
                     [3,4],
                     [5,6]] )

matMul=tf.matmul(data1,data2)
matMul2=tf.multiply(data1,data2)
matAdd=tf.add(data1,data3)

with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matMul2)) # 有点类似于加法
    print(sess.run(matAdd))
    print(sess.run([matMul,matMul2]))
print('end!')  

[[24]]
[[12 12]
 [12 12]]
[[9 9]]
[array([[24]]), array([[12, 12],
       [12, 12]])]
end!


# 初始化操作

In [30]:
import tensorflow as tf
mat0=tf.constant([[0,0,0],[0,0,0]])
mat1= tf.zeros([2,3])
mat2= tf.ones([2,3])
mat3=tf.fill([2,3],15)
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[15 15 15]
 [15 15 15]]


In [36]:
import tensorflow as tf
mat0=tf.constant([[2],[3],[4]])
mat1= tf.zeros_like(mat0)
mat2= tf.linspace(0.0,2.0,11)
mat3= tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[2]
 [3]
 [4]]
[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[-0.48304355 -0.9971061  -0.24124455]
 [-0.8773143   0.3455373  -0.1796714 ]]
