# Tensorflow2.0 小练习

In [36]:
import tensorflow as tf
import numpy as np
import math

## 实现softmax函数

In [90]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    tmp=tf.math.exp(x)
    return tmp/tf.reshape(tf.math.reduce_sum(tmp,axis=-1),(-1,1))

test_data = np.random.normal(size=[10, 5])
# test_data = np.array([20,2.7,0.05])
# softmax(test_data).numpy()==tf.nn.softmax(test_data, axis=-1).numpy()
res=[math.isclose(x,y) for x,y in zip(softmax(test_data).numpy().ravel(),tf.nn.softmax(test_data, axis=-1).numpy().ravel())]
np.reshape(np.array(res),test_data.shape)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [95]:
(softmax(test_data).numpy()-tf.nn.softmax(test_data, axis=-1).numpy())**2<0.001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [101]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    return 1/(1+tf.math.exp(-x))

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [220]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    res=-label*tf.math.log(prob)
    idx = tf.where((res >0) | (res <0))
    output = tf.gather_nd(res, idx)
    return output

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

# test_data=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])  
# prob=tf.nn.softmax(logits)
# label=tf.constant([[0.0,0.0,1.0],[0.0,0.0,1.0],[0.0,0.0,1.0]]) 

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label,test_data))
  - tf.reduce_mean(softmax_ce(prob, label)))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [145]:
def sigmoid_ce(x, label):
    ##########
    '''实现 sigmoid 交叉熵loss函数， 不允许用tf自带的sigmoid_cross_entropy函数'''
    ##########
    return tf.math.reduce_mean(-label*tf.math.log(x)-(1-label)*tf.math.log(1-x))

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 0. 0. 0. 1. 0. 1. 1. 0. 0.]


True